// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wsbqnfdblocklmjaopho.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndzYnFuZmRibG9ja2xtamFvcGhvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ1MzM3OTIsImV4cCI6MjA3MDEwOTc5Mn0.ng0DmGrR_g1o8bZwP_1WDObUMzapCN4D0z_HBhXrs4M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});