// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bfbqqcmcnstmvrpxbutq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJmYnFxY21jbnN0bXZycHhidXRxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQxMDE1NjAsImV4cCI6MjA2OTY3NzU2MH0.-h-0yuYqoWO0YTpI1XLsrpPtbXd-1Q5hN7xkO1y3H7s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});